import React from 'react';
import { ArrowLeft, ArrowRight, Building2, HeartHandshake, Landmark, Users } from 'lucide-react';
interface Props { onBack:()=>void; onSignUp:()=>void; }
export default function PartnerLanding({onBack}:Props){
 const contact=()=>{window.location.href='mailto:support@persona.credit?subject=The%20Founding%20200%20%E2%80%94%20Charter%20Partner%20Application'};
 return <div className="min-h-screen bg-brand-bg px-5 py-6 relative overflow-hidden"><div className="bloom w-[520px] h-[520px] -top-48 -right-28 bg-brand-blue/20"/><div className="max-w-6xl mx-auto relative z-10"><nav className="glass-panel rounded-[1.5rem] px-5 py-4 flex justify-between items-center"><button onClick={onBack} className="text-[10px] font-bold uppercase tracking-widest flex items-center gap-2"><ArrowLeft className="w-3 h-3"/> Persona.Credit</button><button onClick={contact} className="bg-brand-dark text-white px-5 py-3 rounded-full text-[10px] font-bold uppercase tracking-widest">Apply</button></nav>
 <main className="py-20"><section className="max-w-4xl"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-brand-blue">Charter Partner Program</p><h1 className="mt-5 font-display text-6xl md:text-8xl font-light tracking-[-0.045em] leading-[.92]">The Founding <span className="text-brand-blue">200</span></h1><p className="mt-8 text-xl md:text-2xl text-brand-gray leading-relaxed">Before every institution, there is a small group of people who choose to believe before everyone else.</p><p className="mt-6 text-base text-brand-gray leading-relaxed max-w-3xl">PersonaCredit is being built to make cross-border financial identity understandable. The Founding 200 is a permanent group of organizations and individuals who choose to support that beginning — not as investors, employees or promoters, but as the first professional community willing to help shape something they believe should exist.</p><div className="mt-10 flex flex-wrap gap-4"><button onClick={contact} className="bg-brand-blue text-white px-9 py-5 rounded-full text-[11px] font-bold uppercase tracking-[0.14em] flex gap-3 items-center">Apply as a Charter Partner <ArrowRight className="w-4 h-4"/></button><button onClick={onBack} className="glass-panel px-9 py-5 rounded-full text-[11px] font-bold uppercase tracking-[0.14em]">Explore PersonaCredit</button></div></section>
 <section className="mt-24 grid md:grid-cols-3 gap-6">{[[HeartHandshake,'Trust before advertising','Financial products are introduced through trusted relationships. The Founding 200 makes that beginning deliberate.'],[Users,'A limited professional community','Immigration attorneys, relocation experts, founder communities, accelerators, educators and other trusted organizations.'],[Landmark,'A permanent record','The Founding Wall will preserve the names of the people and organizations that helped introduce PersonaCredit before public scale.']].map(([I,t,d]:any)=><div key={t} className="glass-panel rounded-[2rem] p-8"><I className="w-7 h-7 text-brand-blue"/><h2 className="mt-6 text-xl font-semibold">{t}</h2><p className="mt-3 text-sm text-brand-gray leading-relaxed">{d}</p></div>)}</section>
 <section className="mt-24 grid lg:grid-cols-2 gap-8"><div className="glass-panel rounded-[2.25rem] p-9 md:p-12"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-brand-blue">Charter Partner</p><h2 className="mt-4 font-display text-4xl font-light">A role built around judgment, not promotion.</h2><p className="mt-6 text-brand-gray leading-relaxed">A Charter Partner is not a founder, does not receive equity and is not expected to advertise PersonaCredit. The role is simpler: become one of the first trusted organizations willing to introduce the platform before its public release and help improve it through honest feedback.</p><div className="mt-7 space-y-3 text-sm">{['No affiliate commissions','No mass referral campaign','No obligation to advertise','A limited number of personal invitations','Recognition on the permanent Founding Wall'].map(x=><div key={x} className="flex gap-3"><span className="text-brand-blue">✓</span>{x}</div>)}</div></div><div className="bg-stone-950 text-white rounded-[2.25rem] p-9 md:p-12"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-brand-blue">The First 1000</p><h2 className="mt-4 font-display text-4xl font-light text-white">The first community, not a test list.</h2><p className="mt-6 text-stone-300 leading-relaxed">Each Charter Partner receives a limited number of invitations. Together, those introductions form The First 1000 — the first members of the PersonaCredit community.</p><p className="mt-7 text-stone-400 text-sm leading-relaxed">General registration remains available. The Founding 200 is a separate institutional program for trusted introducers; it does not restrict ordinary people from creating a PersonaCredit account.</p></div></section>
 <section className="mt-24 text-center max-w-4xl mx-auto"><Building2 className="w-8 h-8 text-brand-blue mx-auto"/><p className="mt-7 font-display text-3xl md:text-5xl font-light leading-tight">“If you decide that PersonaCredit deserves your trust, we will remember it for as long as PersonaCredit exists.”</p><p className="mt-8 text-brand-gray">Membership is by invitation or application. The program closes permanently once 200 Charter Partners have been confirmed.</p><button onClick={contact} className="mt-9 bg-brand-blue text-white px-10 py-5 rounded-full text-[11px] font-bold uppercase tracking-[.14em]">Apply to The Founding 200</button></section>
 </main></div></div>
}
