import React from 'react';
import { ArrowLeft, ArrowRight, FileCheck2, Gauge, LockKeyhole, ShieldCheck } from 'lucide-react';

type Kind = 'how' | 'what' | 'security';
const content = {
  how: { eyebrow:'How it works', title:'Turn cross-border financial records into a clear financial identity.', intro:'PersonaCredit is designed to make evidence understandable without pretending that one country’s credit system can simply be copied into another.', blocks:[['1. Submit your evidence','Upload identity documents and the financial records that best represent your history.'],['2. Extract and reconcile','The system reads the documents, identifies financial signals and reconciles declared information against documented evidence.'],['3. Apply deterministic rules','Critical classifications use rule-based logic, including contradiction priority and review-required fallbacks.'],['4. Build the report','You receive a structured report with verified evidence, uncertainty, context and TransferScore™.'],['5. You decide when to share','A report link is created only when you choose to publish one. You can revoke it later.']]},
  what: { eyebrow:'What you get', title:'TransferScore™ makes the financial history you already earned portable.', intro:'Traditional credit scores are usually tied to one country. TransferScore™ gives cross-border financial evidence a common 0–1000 signal while keeping the underlying evidence visible, so a recipient can understand both the score and the facts behind it.', blocks:[['What TransferScore™ means','TransferScore™ is PersonaCredit’s proprietary 0–1000 financial-evidence score. It brings together documented income, income consistency, financial obligations, savings and liquidity, evidence quality, and whether the submitted records agree with what you declared.'],['Why it exists','A person can move countries and suddenly become financially unknown to the local system even after years of work, savings and stable financial behavior. TransferScore™ is designed to carry documented financial reputation across that gap.'],['What it does not do','TransferScore™ is not FICO, not a credit bureau score and not a lending, housing or employment decision. It is an additional standardized signal built from the evidence you choose to submit.'],['Verified income view','Documented income is reconciled against declared income and the report explains material gaps.'],['Obligations & cash-flow evidence','Where the submitted records support it, recurring obligations and financial patterns are surfaced.'],['Identity status','Identity evidence is evaluated separately from economic evidence so the report does not hide an identity limitation inside a financial score.'],['Evidence audit','The report preserves the reasons behind important classifications instead of reducing everything to one opaque number.']]},
  security: { eyebrow:'Security & privacy', title:'Sensitive documents should not become permanent baggage.', intro:'PersonaCredit was designed to minimize retention of original uploaded documents and to keep account and shared-report access isolated.', blocks:[['No separate persistent document store','PersonaCredit does not retain original uploaded PDFs or identity images in a separate blob/object-storage system after processing.'],['Paid Gemini processing','Documents are transmitted to the paid Google Gemini API for automated extraction. Under Google’s paid-service terms, submitted content is not used to train or improve Google models.'],['Account isolation','Authentication, report ownership and account data isolation have been tested on the live deployment.'],['Controlled sharing','Public report links are unguessable capability links, are marked noindex/no-store, and can be revoked by the owner.'],['Deletion','Deleting an account removes PersonaCredit account records, assessment history and active share links.']]}
} as const;

export default function PublicInfoPage({kind,onBack,onStart}:{kind:Kind;onBack:()=>void;onStart:()=>void}) {
 const c=content[kind]; const Icon=kind==='security'?ShieldCheck:kind==='what'?Gauge:FileCheck2;
 return <div className="min-h-screen bg-brand-bg px-5 py-6"><div className="max-w-5xl mx-auto"><nav className="glass-panel rounded-[1.5rem] px-5 py-4 flex justify-between items-center"><button onClick={onBack} className="text-[10px] font-bold uppercase tracking-widest flex gap-2 items-center"><ArrowLeft className="w-3 h-3"/> Persona.Credit</button><button onClick={onStart} className="bg-brand-dark text-white px-5 py-3 rounded-full text-[10px] font-bold uppercase tracking-widest">Create My Report</button></nav><main className="py-20"><div className="max-w-3xl"><div className="w-14 h-14 rounded-2xl bg-brand-blue/10 text-brand-blue flex items-center justify-center"><Icon className="w-7 h-7"/></div><p className="mt-8 text-[10px] font-bold uppercase tracking-[0.2em] text-brand-blue">{c.eyebrow}</p><h1 className="mt-4 font-display text-5xl md:text-7xl font-light tracking-[-0.04em] leading-[.98]">{c.title}</h1><p className="mt-7 text-lg text-brand-gray leading-relaxed">{c.intro}</p></div><div className="mt-16 grid gap-5">{c.blocks.map(([t,d])=><div key={t} className="glass-panel rounded-[1.75rem] p-7 md:p-9"><h2 className="text-xl font-semibold">{t}</h2><p className="mt-3 text-sm text-brand-gray leading-relaxed max-w-3xl">{d}</p></div>)}</div>{kind==='security'&&<div className="mt-8 p-6 rounded-[1.5rem] bg-stone-900 text-stone-300 text-xs leading-relaxed flex gap-4"><LockKeyhole className="w-5 h-5 text-brand-blue shrink-0"/><p>The PersonaCredit shield is an internal assurance mark, not an independent security certification or Google endorsement. No security system can eliminate all risk.</p></div>}<button onClick={onStart} className="mt-12 bg-brand-blue text-white px-9 py-4 rounded-full text-[10px] font-bold uppercase tracking-widest inline-flex gap-2 items-center">Start a report <ArrowRight className="w-4 h-4"/></button></main></div></div>
}
